
speech_config:
  mel_layer_type: leaf #Spectrogram/Melspectrogram/leaf
  mel_layer_trainable: True #leaf support train
  add_wav_info: True
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  num_feature_bins: 80
  reduction_factor: 4 #should keep the same with model_config, DS2 : time_reduction_factor *= s[0] for s in 'conv_strides'
  train_list: './test_list.txt'
  eval_list: './test_list.txt'
  wav_max_duration: 7 # s
  only_chinese: True
  streaming: True
  streaming_bucket: 0.5 #s
  pinyin_map: './asr/src/configs/dict/pinyin2phone.map'



inp_config:
  vocabulary: './asr/src/configs/dict/phone.txt'
  blank_at_zero: False
  beam_width: 1
tar_config:
  vocabulary: './asr/src/configs/dict/lm_tokens.txt'
  blank_at_zero: False
  beam_width: 1


running_config:
  batch_size: 32
  train_steps_per_batches: 10
  eval_steps_per_batches: 10
  num_epochs: 10
  outdir: './asr/models'
  log_interval_steps: 300
  eval_interval_steps: 500
  save_interval_steps: 500

